### ISSUE TITLE
Ошибка отображения пустого списка

### ISSUE THREAD

**Issue by vitto88** [sfcl/severcart#130]
При переходе к любому списку картриджей, если он пуст, появляется ошибка 404 Ошибка на стороне сервера.
Снача появлялась при переходе к разделу заправляемых картриджей, но когда передал все пустые на заправку, стала появляться вместо страницы пустых, а заправляемые заработали.
Ошибка вылезла сразу после обновления. Скорее всего связана с тем, что из справочника складов пропал единственный склад и теперь расходники к складу не привязаны. Пришлось лезть в pgadmin и вручную править номер stor_id у всех расходников. Но проблему это не решило.
Версия Python 3.4.2
Версия PostgreSQL 9.4.9
Логи /var/venv/severcart/logs/debug.log
>ERROR 2016-12-28 18:35:37,102 [/var/venv/lib/python3.4/site-packages/django/core/handlers/base.py:284] Internal Server Error: /empty/
Traceback (most recent call last):
  File "/var/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/venv/severcart/common/cbv.py", line 59, in dispatch
    return super(CartridgesView, self).dispatch(*args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/venv/severcart/common/cbv.py", line 21, in dispatch
    return super(GridListView, self).dispatch(*args, **kwargs)
  File "/var/venv/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/venv/severcart/index/views.py", line 514, in get
    return render(request, 'index/empty.html', self.context)
  File "/var/venv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/var/venv/lib/python3.4/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/var/venv/lib/python3.4/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 988, in render
    bit = node.render_annotated(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/base.py", line 955, in render_annotated
    return self.render(context)
  File "/var/venv/lib/python3.4/site-packages/django/template/defaulttags.py", line 168, in render
    len_values = len(values)
  File "/var/venv/lib/python3.4/site-packages/django/core/paginator.py", line 117, in __len__
    return len(self.object_list)
  File "/var/venv/lib/python3.4/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/var/venv/lib/python3.4/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/venv/lib/python3.4/site-packages/django/db/models/query.py", line 112, in __iter__
    for row in compiler.results_iter():
  File "/var/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 807, in results_iter
    fields = [s[0] for s in self.select[0:self.col_count]]
AttributeError: 'SQLCompiler' object has no attribute 'col_count'

**Comment by vitto88** [comment]
Обновил Django до версии 1.9.12
> cd /var/venv/bin && ./pip install Django==1.9.12 && service apache2 restart

Стоит поправить скрипт обновления.

**Comment by sfcl** [comment]
Спасибо. Внёс исправления.
