### ISSUE TITLE
Ошибка в инструкции по обновлению

### ISSUE THREAD

**Issue by mmxbow** [sfcl/severcart#89]
При пошаговом выполнении инструкции после запуска
python3 migrate.py migrate
вылетает ошибка
```
(venv)root@lib01:/var/venv/severcart# python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/var/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/var/venv/lib/python3.4/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/var/venv/lib/python3.4/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/venv/lib/python3.4/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/var/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/var/venv/severcart/conf/settings.py", line 14, in <module>
    from settings_prod import *
  File "/var/venv/severcart/conf/settings_prod.py", line 25, in <module>
    json_data=open(os.path.join(BASE_DIR, 'conf', 'secrets.json')).read()
FileNotFoundError: [Errno 2] No such file or directory: '/var/venv/severcart/conf/secrets.json'
(venv)root@lib01:/var/venv/severcart#
```
после копирования файла
`cp /var/venv/severcart_bak/conf/secrets.json /var/venv/severcart/conf/`
при повторном запуске python3 migrate.py migrate выдало:

````
(venv)root@lib01:/var/venv/severcart# python3 manage.py migrate
Operations to perform:
  Apply all migrations: auth, storages, index, contenttypes, sessions, accounts, docs, service, events
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
(venv)root@lib01:/var/venv/severcart# ls ..
bin  include  lib  severcart  severcart_bak
(venv)root@lib01:/var/venv/severcart#
````

**Comment by sfcl** [comment]
Обновил инструкцию.

**Comment by mmxbow** [comment]
Всё ОК

**Comment by mmxbow** [comment]
Может быть значение версии вынести из settings.py? При копировании settings.py с предыдущего релиза версия будет старой.

**Comment by sfcl** [comment]
При обновлении копируется файл settings_prod.py. settings.py остаётся не тронутым. Версию программы при выпуске нового релиза оставил прежней из-за незначительных изменений.
